### ISSUE TITLE
A request for a new feature

### ISSUE THREAD

**Issue by Alaneczek123123851** [TheonlyIcebear/Bloxlip-Chat-Spammer#2]
Could u make multi-account support???
ty

**Comment by TheonlyIcebear** [comment]
It's already added though? make sure you redownloaded the files

**Comment by Alaneczek123123851** [comment]
I have a problem, it shows [ AUTOBET ] 1:Sent message successfully! Wdym by autobet?

**Comment by TheonlyIcebear** [comment]
How is that a problem it's the print message?
